### ISSUE TITLE
No MidiOut

### ISSUE THREAD

**Issue by dinomaskot** [Opa-/x1-mk1-usb2midi#1]
Midi works great, but midiOut doesn't. Only works in HOTCUE mode.
Known bug or any solutions?

Thanks

**Comment by Opa-** [comment]
Hi, MIDI Out should work just fine, not only in HOTCUE mode.

[MIDIView](https://hautetechnique.com/midi/midiview/) could maybe help you see if anything MIDI is happening while moving knobs etc...

What is your computer and OS version ?
