### ISSUE TITLE
Can't learn on Sonoma / MBP M2 / Traktor 4

### ISSUE THREAD

**Issue by Foxtune** [Opa-/x1-mk1-usb2midi#3]
Hi there,

Just DL the app, green cap on menu bar, X1 LEDs are highlighted but Traktor won't learn any mouvements.

MacbookPro M2 Max / Sonoma 14.4.1
Traktor Pro 4.0.2 13

Also tried with Traktor Pro Plus  3.9.0 90

I've tried change device in Pref / controller manager but X1 seem not be present.
- Traktor Scratch 2 default mapping - Generic Keyboard (Keyboard)
- Traktor. Kontrol Z2. Default (None)

thanks a lot for your work by the way

**Comment by Foxtune** [comment]
do I need the original driver ?

**Comment by Opa-** [comment]
Hi,

No you do not need the original driver.

Also this does not act as a driver, it will emulate a MIDI device. Did you go through all the install procedure and setup MIDI in/out + loaded the `DeckAB.tsi` file into Traktor ?

**Comment by Foxtune** [comment]
This is the answer. Sorry about that
