### ISSUE TITLE
serial code doesn't show 

### ISSUE THREAD

**Issue by TSF-FLAC** [Opa-/x1-mk1-usb2midi#4]
I downloaded the converter app and it shows me only one cereal code ,when I go to controller manager in the in-port out-port section it doesn't show any of the codes , when I plug the x1 mk1 its doest not show me the device to select , I use Ventura 13.5 what did I do wrong ?

**Comment by TSF-FLAC** [comment]
![Uploading IMG_3204.jpeg…]()

**Comment by Opa-** [comment]
> it shows me only one cereal code

How many controllers are you using ?

> when I go to controller manager in the in-port out-port section it doesn't show any of the codes , when I plug the x1 mk1 its doest not show me the device to select

Did you download `DeckAB.tsi` file and imported it into Traktor ?

---

I can't see your uploaded picture, could you try to re-upload it ?
Also what version of Traktor are you using ?
